apiVersion: apps/v1
kind: Deployment
metadata:
  name: produtos-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: produtos
  template:
    metadata:
      labels:
        app: produtos
    spec:
      containers:
        - name: produtos
          image: calegari/produtos
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: market  
            - name: MONGO_URI
              value: 'mongodb://produtos-mongo-srv:27017/produtos'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: produtos-srv
spec:
  selector:
    app: produtos
  ports:
    - name: produtos
      protocol: TCP
      port: 3000
      targetPort: 3000
